//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPEscuela.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumnos
    {
        public Alumnos()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        [Display(Name = "Id del estudiante")]
        public int Id_Alumnos { get; set; }

        [Display(Name = "Numero de la Matrícula")]
        public int Matricula { get; set; }

        [Display(Name = "Nombre del estudiante")]
        public string Nombre { get; set; }

        [Display(Name = "Apellido del estudiante")]
        public string Apellido { get; set; }

        [Display(Name = "Dirección del estudiante")]
        public string Dirección { get; set; }

        [Display(Name = "Correo del estudiante")]
        public string Corre_electronico { get; set; }

        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }

        [Display(Name = "Numero de inscrito")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
    }
}
