//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPEscuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public Aula()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        public int Id_Aula { get; set; }
        public string Salon { get; set; }
    
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
    }
}
