//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPEscuela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int Id_Inscripcion { get; set; }
        public int IdAlumnos { get; set; }
        public int IdAsignatura { get; set; }
        public int IdMaestros { get; set; }
        public int IdAula { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Asignatura Asignatura { get; set; }
        public virtual Aula Aula { get; set; }
        public virtual Maestros Maestros { get; set; }
    }
}
