//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPEscuela.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDmodels : DbContext
    {
        public BDmodels()
            : base("name=BDmodels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alumnos> Alumnos { get; set; }
        public DbSet<Asignatura> Asignatura { get; set; }
        public DbSet<Aula> Aula { get; set; }
        public DbSet<Inscripcion> Inscripcion { get; set; }
        public DbSet<Maestros> Maestros { get; set; }
    }
}
